[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/gif-land/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"


[[main.block]]
format = "md"
content_file = "input/pages/index/index.md"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
