[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/index/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<main id=\"main\">"

[[main.block]]
format = "html"
content_file = "input/pages/index/content.html"

[[main.block]]
format = "md"
content_file = "input/pages/index/about.md"

[[main.block]]
format = "md"
content_file = "input/pages/index/portfolio.md"

[[main.block]]
format = "md"
content_file = "input/pages/index/market.md"

[[main.block]]
format = "md"
content_file = "input/pages/index/pet-project.md"

[[main.block]]
format = "md"
content_file = "input/pages/index/back-end.md"

[[main.block]]
format = "html"
content = "</article>"

[[main.block]]
format = "html"
content = "</section>"

[[main.block]]
format = "md"
content_file = "input/pages/index/cv.md"

[[main.block]]
format = "md"
content_file = "input/pages/index/contact.md"

[[main.block]]
format = "html"
content = "</div><div id='right'></div>"

[[main.block]]
format = "html"
content = "</div></main>"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
