[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/portfolio/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"

[[main.block]]
format = "html"
content_file = "input/pages/portfolio/index.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
