[main]

[[main.block]]
format = "html"
content_file = "../global/elements/head.html"

[[main.block]]
format = "html"
content = "<meta property='article:section' content='Portfolio' />"


[[main.block]]
format = "html"
content_file = "../global/elements/navbar.html"

[[main.block]]
format = "html"
content = "<nav id=\"breadcrumbs\" aria-label=\"Breadcrumbs\"></nav>"


[[main.block]]
format = "html"
content = "<body>"


[[main.block]]
format = "html"
content = "<main id=\"main-port\">"

[[main.block]]
format = "html"
content = "<div id=\"toc-container\" class=\"toc-class\"></div>"

[[main.block]]
format = "document"


[[main.block]]
format = "html"
content = "</div></main>"


[[main.block]]
format = "html"
content_file = "../global/elements/footer.html"

[[main.block]]
format = "html"
content = """\
	<script src='/js/toc.js'></script>\
	<script src='/js/breadcrumbs.js'></script>\
"""


